# Form implementation generated from reading ui file '.\SegmentWidget.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(420, 118)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.segBox = QtWidgets.QGroupBox(parent=Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.segBox.sizePolicy().hasHeightForWidth())
        self.segBox.setSizePolicy(sizePolicy)
        self.segBox.setMinimumSize(QtCore.QSize(0, 100))
        self.segBox.setObjectName("segBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.segBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.rampRadioButton = QtWidgets.QRadioButton(parent=self.segBox)
        self.rampRadioButton.setObjectName("rampRadioButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.rampRadioButton)
        self.holdRadioButton = QtWidgets.QRadioButton(parent=self.segBox)
        self.holdRadioButton.setChecked(True)
        self.holdRadioButton.setObjectName("holdRadioButton")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.holdRadioButton)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.targetLabel = QtWidgets.QLabel(parent=self.segBox)
        self.targetLabel.setEnabled(False)
        self.targetLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.targetLabel.setObjectName("targetLabel")
        self.horizontalLayout_4.addWidget(self.targetLabel)
        self.targetDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.segBox)
        self.targetDoubleSpinBox.setEnabled(False)
        self.targetDoubleSpinBox.setDecimals(1)
        self.targetDoubleSpinBox.setObjectName("targetDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.targetDoubleSpinBox)
        self.rateLabel = QtWidgets.QLabel(parent=self.segBox)
        self.rateLabel.setEnabled(False)
        self.rateLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rateLabel.setObjectName("rateLabel")
        self.horizontalLayout_4.addWidget(self.rateLabel)
        self.rateDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.segBox)
        self.rateDoubleSpinBox.setEnabled(False)
        self.rateDoubleSpinBox.setObjectName("rateDoubleSpinBox")
        self.horizontalLayout_4.addWidget(self.rateDoubleSpinBox)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.timeLabel = QtWidgets.QLabel(parent=self.segBox)
        self.timeLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_5.addWidget(self.timeLabel)
        self.timeDoubleSpinBox = QtWidgets.QDoubleSpinBox(parent=self.segBox)
        self.timeDoubleSpinBox.setDecimals(1)
        self.timeDoubleSpinBox.setMaximum(1000.0)
        self.timeDoubleSpinBox.setObjectName("timeDoubleSpinBox")
        self.horizontalLayout_5.addWidget(self.timeDoubleSpinBox)
        self.formLayout_2.setLayout(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.segBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.segBox.setTitle(_translate("Form", "Segment 1"))
        self.rampRadioButton.setText(_translate("Form", "Ramp"))
        self.holdRadioButton.setText(_translate("Form", "Hold"))
        self.targetLabel.setText(_translate("Form", "Target:"))
        self.targetDoubleSpinBox.setSuffix(_translate("Form", " °C"))
        self.rateLabel.setText(_translate("Form", "Rate:"))
        self.rateDoubleSpinBox.setSuffix(_translate("Form", " °C/s"))
        self.timeLabel.setText(_translate("Form", "Time:"))
        self.timeDoubleSpinBox.setSuffix(_translate("Form", "s"))
